### ISSUE TITLE
Port to GTK+3

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/jam-media-explorer-activity#1]

**Comment by quozl** [comment]
https://github.com/fdanesse/JAMediaSuite is the upstream repository, please use the sources there.

**Comment by tony37** [comment]
Whereever you get the sources, please make sure the pull request puts 
the correct source in the Sugarlabs github and that the change in 
version is correctly reflected in activity.info and in ASLO.

Tony
